(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 480,
	height: 84,
	fps: 24,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.leaf_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgJArIgBAAIgCgCQgLgOAAgNQAAgMAIgKQAIgMAKgKQAJgGALgGIAAAAIABACIgBAAQAAACgFACIgHAEQAKAUgEAVQgFATgSAPIgDAAgAAEgbQgTARgEAUQgDAPAMANIACADQAXgSAAgXQABgIgCgHQgCgIgEgHIgEADg");
	this.shape.setTransform(-2.4,4.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.247)").s().p("AgMAhQAGAAAKgVQAMgSgOgaIAEgDQAEAHACAIQACAIgBAIQAAAWgXASIgCgDg");
	this.shape_1.setTransform(-2.2,4.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#663333").s().p("AgQAGQAEgXAXgSQAEAHABAIQACAIAAAIQgBAWgWASQgPgOAEgQgAAAgDQgDAMABAPQAAgKACgKIAIgaIgIATg");
	this.shape_2.setTransform(-2.7,4.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgJArIgBAAQgNgPAAgOQAAgMAIgKQANgUAZgOIABACQAAACgGACIgHAEQAKAUgEAVQgFATgSAPIgDAAgAgTAKQgDARAOAOQAXgSAAgXQABgIgCgHQgCgIgEgHQgWASgFAWgAAAAAIAGgSIgIAaQgDAKAAALQgBgPAGgOg");
	this.shape_3.setTransform(-2.4,4.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.8,0,4.9,8.7);


(lib.leaf_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgJArIgBAAIgCgCQgLgOAAgNQAAgMAIgKQAIgMAKgKQAJgGALgGIAAAAIABACIgBAAQAAACgFACIgHAEQAKAUgEAVQgFATgSAPIgDAAgAAEgbQgTARgEAUQgDAPAMANIACADQAXgSAAgXQABgIgCgHQgCgIgEgHIgEADg");
	this.shape.setTransform(-2.4,4.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.247)").s().p("AgMAhQAGAAAKgVQAMgSgOgaIAEgDQAEAHACAIQACAIgBAIQAAAWgXASIgCgDg");
	this.shape_1.setTransform(-2.2,4.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666600").s().p("AgQAGQAEgXAXgSQAEAHABAIQACAIAAAIQgBAWgWASQgPgOAEgQgAAAgDQgDAMABAPQAAgKACgKIAIgaIgIATg");
	this.shape_2.setTransform(-2.7,4.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgJArIgBAAQgNgPAAgOQAAgMAIgKQANgUAZgOIABACQAAACgGACIgHAEQAKAUgEAVQgFATgSAPIgDAAgAgTAKQgDARAOAOQAXgSAAgXQABgIgCgHQgCgIgEgHQgWASgFAWgAAAAAIAGgSIgIAaQgDAKAAALQgBgPAGgOg");
	this.shape_3.setTransform(-2.4,4.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.8,0,4.9,8.7);


(lib.leaf = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgJArIgBAAIgCgCQgLgOAAgNQAAgMAIgKQAIgMAKgKQAJgGALgGIAAAAIABACIgBAAQAAACgFACIgHAEQAKAUgEAVQgFATgSAPIgDAAgAAEgbQgTARgEAUQgDAPAMANIACADQAXgSAAgXQABgIgCgHQgCgIgEgHIgEADg");
	this.shape.setTransform(-2.4,4.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.247)").s().p("AgMAhQAGAAAKgVQAMgSgOgaIAEgDQAEAHACAIQACAIgBAIQAAAWgXASIgCgDg");
	this.shape_1.setTransform(-2.2,4.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#669900").s().p("AgQAGQAEgXAXgSQAEAHABAIQACAIAAAIQgBAWgWASQgPgOAEgQgAAAgDQgDAMABAPQAAgKACgKIAIgaIgIATg");
	this.shape_2.setTransform(-2.7,4.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgJArIgBAAQgNgPAAgOQAAgMAIgKQANgUAZgOIABACQAAACgGACIgHAEQAKAUgEAVQgFATgSAPIgDAAgAgTAKQgDARAOAOQAXgSAAgXQABgIgCgHQgCgIgEgHQgWASgFAWgAAAAAIAGgSIgIAaQgDAKAAALQgBgPAGgOg");
	this.shape_3.setTransform(-2.4,4.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.8,0,4.9,8.7);


(lib.leaf_tree_ani = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.leaf();
	this.instance.setTransform(4.3,0.6,1,1,-19.7,0,0,-0.4,0.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-38.2,y:0.5},7).to({rotation:-25.3,y:0.4},9).to({rotation:-46.3,y:0.5},5).to({regY:0.5,rotation:-29.5,x:4.4},6).wait(5).to({regY:0.4,rotation:-19.7,x:4.3,y:0.6},4).to({scaleX:1,scaleY:1,rotation:-11.9,x:4.4,y:0.5},7).to({rotation:-26.2},5).to({scaleX:1,scaleY:1,rotation:-19.7,x:4.3,y:0.6},7).to({regY:0.3,rotation:-39.2,y:0.5},7).to({regY:0.4,rotation:-44.2,x:4.4},4).to({rotation:-30.9,x:4.3},6).to({regX:-0.5,rotation:-39.4},8).wait(7).to({regX:-0.4,rotation:-27.7,x:4.4},4).to({rotation:-32.4,x:4.3},6).to({rotation:-25.2},4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,7.5,9.8);


(lib.leaf_gust_ani_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 6
	this.instance = new lib.leaf_2();
	this.instance.setTransform(-62,-16.3,1.498,1.498,-19.6,0,0,-0.4,0.3);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(19).to({_off:false},0).to({rotation:340.4,x:-39.5,y:92.7},49).to({_off:true},1).wait(155));

	// Layer 5
	this.instance_1 = new lib.leaf_2();
	this.instance_1.setTransform(50.5,-16.3,1.498,1.498,-19.6,0,0,-0.4,0.3);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(174).to({_off:false},0).to({rotation:340.4,x:28,y:92.7},49).wait(1));

	// Layer 4
	this.instance_2 = new lib.leaf();
	this.instance_2.setTransform(90.5,-16.3,1.498,1.498,-19.6,0,0,-0.4,0.3);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(39).to({_off:false},0).to({rotation:-379.6,x:93,y:92.7},49).to({_off:true},1).wait(135));

	// Layer 3
	this.instance_3 = new lib.leaf_1();
	this.instance_3.setTransform(215.5,-16.3,1.498,1.498,-19.6,0,0,-0.4,0.3);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(154).to({_off:false},0).to({rotation:-379.6,x:210.5,y:92.7},49).to({_off:true},1).wait(20));

	// Layer 1
	this.instance_4 = new lib.leaf();
	this.instance_4.setTransform(155.5,-16.3,1.498,1.498,-19.6,0,0,-0.4,0.3);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(79).to({_off:false},0).to({rotation:340.4,x:115.7,y:92.7},49).to({_off:true},1).wait(95));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.leaf_gust_ani = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 6
	this.instance = new lib.leaf_2();
	this.instance.setTransform(220.5,-16.3,1.498,1.498,-19.6,0,0,-0.4,0.3);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(119).to({_off:false},0).to({rotation:340.4,x:240.5,y:92.7},49).wait(1));

	// Layer 5
	this.instance_1 = new lib.leaf_2();
	this.instance_1.setTransform(50.5,-16.3,1.498,1.498,-19.6,0,0,-0.4,0.3);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(79).to({_off:false},0).to({rotation:340.4,x:28,y:92.7},49).to({_off:true},1).wait(40));

	// Layer 4
	this.instance_2 = new lib.leaf();
	this.instance_2.setTransform(405.5,-16.3,1.498,1.498,-19.6,0,0,-0.4,0.3);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(39).to({_off:false},0).to({rotation:340.4,x:425.5,y:92.7},49).to({_off:true},1).wait(80));

	// Layer 3
	this.instance_3 = new lib.leaf_1();
	this.instance_3.setTransform(300.5,-16.3,1.498,1.498,-19.6,0,0,-0.4,0.3);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({_off:false},0).to({rotation:-379.6,y:92.7},49).to({_off:true},1).wait(110));

	// Layer 1
	this.instance_4 = new lib.leaf();
	this.instance_4.setTransform(155.5,-16.3,1.498,1.498,-19.6,0,0,-0.4,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({rotation:340.4,x:115.7,y:92.7},49).to({_off:true},1).wait(119));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,-16.9,11.2,14.7);


// stage content:



(lib.Autumn_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// ani_front
	this.instance = new lib.leaf_gust_ani_2();
	this.instance.setTransform(124.9,7.2,1,1,0,0,0,5.6,7.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// text
	this.text = new cjs.Text("1st MARCH - 31st MAY", "15px 'Sports World'");
	this.text.textAlign = "center";
	this.text.lineHeight = 19;
	this.text.setTransform(238,63.1);

	this.text_1 = new cjs.Text("AUTUMN SEASON", "30px 'Sports World'", "#FF9900");
	this.text_1.textAlign = "center";
	this.text_1.lineHeight = 36;
	this.text_1.lineWidth = 476;
	this.text_1.setTransform(236.4,21.9);

	this.text_2 = new cjs.Text("AUTUMN SEASON", "30px 'Sports World'", "#BF7000");
	this.text_2.textAlign = "center";
	this.text_2.lineHeight = 36;
	this.text_2.lineWidth = 476;
	this.text_2.setTransform(238,23);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.text_2},{t:this.text_1},{t:this.text}]}).wait(1));

	// ani_bg
	this.instance_1 = new lib.leaf_gust_ani();
	this.instance_1.setTransform(-7.6,7.2,1,1,0,0,0,5.6,7.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Layer 4
	this.instance_2 = new lib.leaf_tree_ani();
	this.instance_2.setTransform(251.1,23.7,1.5,1.5,0,0,0,3.7,4.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Layer 5
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AHun6QAJASAIAYQACAKADAKQATBLgQBDQg+AClYg6QlWg7g7ACQhBADirAsQinAqgVAAQgMAAhggKQhNgIgWAFQgXAGhvA6IhqA5IBugoQBygqAXgFQAZgFBgAPQAwAHAsAIICagdIABAAIAigGQgJA0gJAMQgVAci0BrQDghmAQgPQAJgKAFgoQACgUAAgTICDgYIApgHIFNBoQFYBzAxA7QAzA/AOBWQALBHgPA1QgIAfg+AeQhQAogdAbQgpAohYAeIhQAWIkMBZIJ5gKIB+gnQCJgmA3ABQA5ACB4AhQA9ARAxARIBcAAIgFuGIhAgSIh0giIiBglg");
	this.shape.setTransform(368.2,38.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#331400").s().p("AjfHcQA+ABAigrIAHgKQACAegsAQQgXAIgUAAQgJAAgJgCgAAHHbIgBgCQgBgEAGgBIACgBQAGgGAEgIIABgBQAKgCALgEQAFgCAEgEQAIgIAKgEQAMAAAMADQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAABABQgPACgPAGQgLADgKAJQgHAHgMgBIgBACQAAAFgGADIgCABQgCAGgFAAIgFgBgABKHQQA+ACArgrQAAAAABAAQABgBAAAAQABAAAAAAQABAAAAAAQgNAbgjAMQgTAHgQAAQgOAAgMgEgAMJG6QgygNgbgVQAqAPArAJQAjAIAaAVQgggKglgJgAAZGAQAMgTAOgPQgKA5gyAdQgnAWgiABQBGgRAlg6gAEHG7QAOgNARgJQAggQAfgSQAVgMAYgFIA1gNQAtgLAoALQAfAKAdAMQgIgPAFgTQgDgHgBgHQgCgMADgHQAAAPAEANQAGgRAHgMQgFASgEATQADAJAGAHQAEAFAGADQAMAHAJALQgagMgPgaIgBAGQgCALAFAKIAGAMQgGgFgDgGQhcgXhiAZQgtAMgpAWQgSAKgVAHIAAACIAAACIgBACIgCABIgFACIgFACIgDAAQgDAAgDgBgAMuD+QgRgjgOgjQgUgxAlgeIAFAEQgFgTAEgiQAKhNgBhNIgCgXIAKAtQAHAlgGAjQgLA4gEA7QAZAYAAAnQAAAfgWAVQAqAuAABBQgBA1gMApQAOhggnhRgAD0FIQA7gPAmgpQAUgWAMgZQACAageAdQgqAog7APQhJATgEBKQgKhNBXgXgAEIFvQA0gzBEgRQAFAAAGACIABACQhBAPguAvQgoAngoAUIA7g5gAMPGYQAwg2gohKQgcgzgGgvQAkBEAUBKQARA/guAXgADHElQBfgYAphSQAJgTAFgRQgJBwh7AiIgaAHQhPAWACBLQgNhUBigYgALDC6QgKgiAEgjQAEgkAPgbQgfBoAqBmQAdBFgEBDQgVhmgchsgAKKDZQAPhegdhbQgXhDAGhMQADgyAcgjQgxBSAeBiQAsCLgVCYQgDAVAKARQAZAvAjAgQhag7ATh0gAGYFGQAJgKAKgIQgOgMgGgTQgMgBgLgCQALABAMgBQgDgKAAgNQAAgSAIgNQgJAcAIAaQAYgCAVgJQgCgIgBgKQgBgPAJgJQgIAUAIAUIARgJIAGgEQgJAMgMAHIAEAGQAJAQARAJQgZgHgKgWQgMAFgQACIgSABIAHAOQAEAJAGAGIANgHQADADgNAHQAKAJAOAFQgPgEgLgIQgUANgJAVQgEAIgEAAQAGgPAJgMgAIFEsQAogBAYAZQgegOgigKgAJdECQgIgEgGgFIgGAFQgOAKgPAAQARgGANgOQgJgIgBgJQAFAIAHAGQAFgFAEgIQADgGABgIQgBAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAQADASgMAPIAMAHIABABIABgCQAGgQAKgNQgJAPgEASIAWAKQgMgBgLgFIgBAHQgCASAPAKQgXgKAHgbgAIJEEQAQgVASgTQAHgHAEgJIACgBIAJgDQA8heg1hqQhBiABJh6QA/hqgkhwQAxCBhLB+QhABsA8BzQA2Bpg8BcIgDABIgHABQgJAagUARQgJAIgLAAIgDAAgAEHDMIAEgaIAAAAQAJAigVAZQgPATgSAEQAngRACgngAGbDAQgLABgKgDIAXgDIABgCQAPgZAcgKQgBAFgOAGQgSAJgHAQIAagFIAGgBQgLAJgWADIgCAAIgCALIgDAPQgDgNAFgNgAEqDUIgEAAQgFgFgBgHQAAgIADgGQgHgGgFgJQgFgIAEgGQAFAPAMAKQAHgKANgEIAIABQAFAAADAEQgQgGgPAOIgDADIAAAAQAIAGAIAEIAFADQgNgBgLgHQgGALALAMIgBAAgAIVBDQAGhTgjhNIAFAGQAvBXgQBjQgOBPhJAdQBLgvAFhdgAGxgNIgMg2IAKAYQAuBlhABZQgNASgQAHQBLhOgahrgAE0A6QgGgugJgeQAgAwgDBBQgCAygYAVQATgxgHg7gAFdCDQgGAGgGAHQgCADgDgBQAHgKAJgJIgBgPQgBgPAFgLQgDATAEASQATgQAYgCIgXAKQgKAFgJAHIABAGQAGAPANALQgSgIgGgUgAJ9BrQgCgOgFgLQgDAKgGAIQAEgLABgNIgGgIIAGAGQABgLgBgMQgDgOgIgLQgCgDgBgCQgHAFgGABIARgOIAIgIQgBAIgIAGIADAFQABADACAAQALATgBAXIgBAJQAOAQAAAYQAAAWgLAQQAIgWgEgbgAENCPIgOAGQAHgDAGgFQgDgGABgDIAFAGQAHgGAEgIIAFgIQADAPgPAJIgBABIACACQADAGAFAEQgJgBgGgJgAI8B2QgGgIgIgGIAAgCIABgDIABgBIANARQADgKgBgMQgCgOABgJQAIAXgHAYIADAFIABABIAGgOQACgGADgDQABAIgEAIQgDAGgFACQAHAJgCAKQgDgKgFgKIgCgDIgBABQgHAUgTADQATgKAGgQgAHTBMQAMgWASgOQgOAQgJATQAMAHAIANQAFAKgFAJQAAgMgIgKQgGgKgHgGIgEAIQgHASAAATQgGgXALgWgAMJgfQACgtgMgtQgJgpgOgnQgDgIAGAAQAyBbgQBpQgIArgFArQgDAcgVAMQAfhAAChQgAESBNQgFAGgHADQAIgIAFgKQABgPgDgQIgBABQgGAMgLAHQAKgNAGgPQgHgWgPgQQgEgFAEgCQAPASAIAZIACgGIAGgUQACASgIAQIAEAUIAAAHIAAgBIAGgLQAAAMgGALQgDATgMAPQAIgOADgQgAGgBIIgBgXIAAgGIgIgFQgIALgMABQAKgGAGgIIgBgBQgNgGAAgEQAJADAHAFIAGgLQgNgKgIgQQgFgKAEgIQAAATANANIAJAKIABgEQACgKACgGQACAMgEALIAGAFIgGgEIgGALIAJAGIACAOIABAXQAAAEgEADIAAgNgAFdAyQAAgKACgGQAHARgKAOQgGALgKAFQAPgMACgTgAFxBNQAGhlg0hgQgZguAVgyQAxhzAZh0QgFBogyBfQgqBPAsBMQAsBNgFBUQAAAJgIAAIgCAAgALQg8IAJAQQAZAkgJAnQgGgtgTgugAH0AXIgRgTIgDgDIgLAMIAIgNQgHgGgJgEIgBgEQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAgBIAAAAQABABAAAAQAAAAABAAQAAABAAAAQAAAAAAABIABACQAIAEAHAFIANgVIAAAAQgDgNAFgJQgBAJABAKQAFgJADgLIABAAQgBAPgHANIACAFIAHATQgHgGgDgOIgFAHIgHAIIAHAFIANAQQAKgCADAEQgDADgEAAQgEAAgEgDgAFEAJIACgDQgHgGgEgLQgCgJADgGQAAARAKAKIACABIAGgGIAAgBIAEABIABAAQgGAEgDAEQAHAGAHAEQgJgBgGgFIgGAOQgDgHAEgGgAK6gdQgGAGgHAEQgNAJgOgDQAXgFAOgQQgGgLgMgJIgCACIgQAPQgGACgFAAQAOgJALgNIgFgDQgPgJADgUQAEgTAOgMQgUAZAMAeQABADADACIAEADIAEgGIALgOQgBANgLAKQALAIAIALIAFgGQADgGAFgEQgDALgHAJIADAGQAJASgJAMQADgSgHgQgAJEgsQgDgGgBgFIgCgCQgJgFACgDIAIAFIABgEIAAAEQAKAGAHAIQAKAJAAALQgDgEgDgGQgCgGgEgEIgCgCIgLgGQAEAMAJAKQAIALAEAMQgMgPgLgUgAHTg7QgEALADAMQgIgJAJgOgABviYQgtgLgqgWQhJgmhAgfIAAAAQB0ArBzA2QApATAjATQAsAZAGAwQgkhUhhgWgAJXhCIgFgIIAAADQABAKgCAKQgDgJgCgQQAAgFgCgEQgGgHgIgEIABAAIAGACQAAAAAAgBQAAAAAAAAQAAgBAAAAQABAAABAAQAFADADAFQAHAGAFAJQAGAMAEALQgGgCgGgOgAEXhBQgGgEgFgGIgLALQgEADgEgCIARgQIgDgEQgEgKgCgLQgBgEADgBIABAAQAAAHACAHQACAGgBAFIADAEQAJgKAHgLQAHgKAFgJQgEAWgRARIgEAFQAFAGAGAEQAJgIAHgKQAHgJABgIQgBAUgQAPIgCACQAPAHAWgEIABABQgZAFgPgIQgKAHgKADQAJgFAHgHgAGChnQAIgQAMgLQgKAQgKAVQgFANgBAPQgEgSAKgUgALHhPQgUgsAfgcQgVApAPAoIgFgJgAHchtQgCgGADgCQAJAXgLAUQAGgQgFgTgAJah2IgEgGQgJgQgPgCQAPgBAIALIAFAGIgBgQQgBgNgBgMQgIAEgGAHQgLALgHANQABgLAIgJQAKgLAMgHIgDgMIAFALIAKgFIAEABIABABQgIACgGAEQAGAVABAXQgBAVAFATQgHgPgDgTgAJXhmQgJgQgPgCIAAgBQAPAAAJALQAIAIgDAKIgFgKgAHGiPIAEgEIgGgIQgEgKAEgHQAAANAIAKIAMgKQgBgMAEgLQAEgNAFgMQADAEgFALQgHAOABARQAPgLASgHIADABIAAABQgUAIgRAMIgCACIgLAJIAHAGQAMAIANAGQgWgBgNgRQgRARgFAVQgBgUASgRgADAiQIAAAAIgLgGIAHADIADABQgDgLADgJQABALAEAKIAZAIQgNgBgLgEIAEAKIAOAWQgQgLgHgXgAG1kXQAuhQAEhaQABBngwBZQgmBDAHBEQgPhTArhKgAKPjEQgBgzAlg1QARgZAEghQAEggAGgXQAGAZgEAcIgFAlQgEADgEACIgCACQAAAIgEAFQgDAGABAGQgjApgHA5QgDAbAKAZQgNgbAAgcgAFri0IAFgLQgNgIgEgTQgBgFABgFIABAAQADAUAPANIAAABQAFgHAIgFIgIAPQAIAGALAAQgMAAgJgDQgJAQgBASQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBAAQgCgOAEgQgAMYiwQgkhBgFg/QAfBJAVBQQgEgNgHgMgADpiaIgBgBIgBgDIgDgGQgggNgggPQgxgYgsgJIABAAQA4AAAyAYQAlARAYAcIgCACIgCABIgCgBgACjijQgIgJAEgJQABANAIAIIgFgDgAEFi5QgHAJgKAFQAKgHAGgJIgGgJQgPgVgagLQgBAAAAgBQgBAAAAAAQAAAAABAAQAAAAABAAQAdAKASAWIADAFQAHgMABgQIABgIIgMAAIAMgBIADgQIACAPQANgEAKgIQAKgHAFgJIAAAAQgGAXgbAFIgFABQAAASgIAQIgEAGQAIANACAPIgOgYgAK9jVIACgHIgLgIQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIABAAIAMAGQAGgNAMgLQACAEgIAJQgHAGgDAGIAKAEIAGACQACgRAOgIQgKAKgCAPIAKACIAAAAIgKABIAAAFQgBANADAMQgHgKABgUQgKgBgIgEQgFANADAQIADAPQgLgPAGgXgAHHjnIgEgbQAKATgCAZQgBASgMAIQAMgTgDgYgAM2lMQgHgyAQgoQgIBFAUBEQAOAuAFAtQgcg/gMhLgAJajPIgBgDQAMANANgLQgDgMAFgPQAGgSAMgLQgKAQgGAVQgCAJAAAHIADgEIAKgMQgBAMgJAIIgCABIACAIIgEgGIgLAHQgKgDgEgHgAgHkCIAAgDIgHgBIgGgBIAEAMQADAJAHAIQgMgIgFgSIgBgEQgMgDgKgHQAAAAgBgBQAAAAAAAAQAAgBABAAQAAAAABAAIAUAIIAAgJIADAJIAPAEQgBgLACgIQAAAKACAKIAEABQARADAPAGIgkgHQADANAEANQAFALANAHQAEACADADQgfgJgEgmgAIMjpQgGgPACgKQABgJACgEIAGgIIgMgHIgJAOIgGAMIgGAJIgEAJIgDAKIgCAAIgBgBIABgGIACgGIADgEIAFgLIAFgHIAEgHIAJgNIgBgBIgMgGIgBgBIgFAFIgDADIgRAKQgCABgFAHIgBgGIACgBQABgCAEgCIAGgEIAHgEQAHgDACgFIgDgBIgIgCIgIAAIACgBIACgDIAGABIAIADIADABIABgBQABgCgBgGIgBgHIAEgBIABALIgCAHIABABIAHADIAFADIAIgNIAKgLIAAAAQAagsgDg4IgEg2IgBgJIAFAJQARAugJAyQgHAkgXAXIACAAIgFAFIgGAIIgGAMIALAHIAFgEQAFgCAKAAIAKACIABABIAAABIgDAAQgSgBgCABIgFADIAQANQAIAGAEAFIgCADQgEgGgIgGIgQgMIgHALIgBAEIgBAFIAAAGIAAAGQAGAOACABIABAEIAAAAIgCABIgFgIgACWj5QgQgGgPgJIgQAZQADgNAJgNIABgBIgNgKQgMgKAAgLQAKASAQALQAHgKALgIQAQAJACAVIABAFIAcAKQgOgCgOgFQAAAKgCAIIgCgTgACGkWQgGABgDAFIgFAHQAJAFAKADIALAEIgBgGQgCgTgMAAIgBAAgAGXksQgHAFgIADIgPAFQAQgIANgKQgBgQACgNIABAcIAGgGQAIgGADgKIAGgYQADAdgXAUIgDACIgBAVQgBAUgRAIQAUgUgCgcgACpkNQAvAKA4gSQAIgCAHgEQgBAUgpAHQgKACgKAAQgfAAgZgPgAhJksQgngBgmgEQAbACAcgCQBngHBUAtQhNgdhYgEgAKVkYIgFgFQgGAEgGABIAJgIIgFgGIAHAEQAIgKADgOQgMAEgKgDQAMAAALgEIAFgQIAAANIAKgHQACgDADAAQgFAJgKAFQgCALgGAKIgGAHIAIAGQAFAHgCAHQgCgHgGgFgAMGk6QgEgMgHgKIgBADQgKAVgTAIQAWgNAGgVQgHgIgJgFIAAAAQAJAEAHAGQACgHAAgJQgBgNgJgLQgEgFADgCQAVAWgJAcQALALAFARQAGAVgGASQABgWgHgVgAI2lEQgBgcAdgEIADABIABABQgYACgBAVIgFAhQgCgMAAgOgAkPlDQgsgJgGgUQA4AdA8AMQgigFgggHgAMPliQACgQAOgKQgPAQADAYQACAPAMALQgWgLAEgdgAtdk+IBAgTQBUgcBXgGQANABALACQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABQhFAAhAAXIgJADQgeANgeAFQgYAFgYAAIgLgBgAH1lZIgGADIAFgDQgCgHgBgJQAAgKAEgGQgBAPAFANQAVgSAHgcIAGgYQAEAdgTAYQgIALgLAHIACAGQAEAHAJAEQAEABADACQgUgCgGgPgAJcmJQgDgTAAgQQAIAYACAbQACAUgIAPQAFgZgGgagAE+mYQgDgcgIgTQAZATAAAjQAAAYgDAWQgHgWgEgfgAHImSIgBABQgLAJgNACQgHAOgLAJQAJgKAFgNQgHAAgHgBIAPgBQADgKACgLIgFADIgXALQAOgKAPgNQAAgSgMgKQAOAKACAOQAGgFACgIQABAMgIAJQAAAJgEAKIgDAGQAQgDAIgIIAAgFIgGgiQAIARABASQAKgMgCgUQAAgHgDgGIABgBQAUAbgZAWIgBAQQgDAVgNAMQAQgVgDgZgAKjmVQgNAEgMgCQANgBALgFIgBgEQgFgUgQgPQgBgBAAAAQAAgBAAAAQAAAAAAAAQABgBABAAQAUARAEAYQAMgFAKgJQgFgVgTgMIAAAAQAVALAGATIAJgKQAFgGAGgFQgGAPgNALQACAIAAAJQgBAYgOAQQANgYgDgcIgBgBIgNAIIgJAEIAAAMQgBAPgJAOQgFAGgFABQAVgUgDgbg");
	this.shape_1.setTransform(393.8,38.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#663300").s().p("ABiGiIBQgWQBXgeAqgoQAdgbBQgoQA+geAIgfQAPg1gLhHQgOhWg0g/Qgvg7lZhzIlNhoIgpAHIiDAYQAAATgDAUQgEAogJAKQgQAPjgBmQC0hrAVgcQAIgMAKg0IgjAGIAAAAIibAdQgrgIgwgHQhhgPgXAFQgYAFhyAqIhuAoIBqg5QBvg6AXgGQAWgFBNAIQBgAKANAAQAUAACngqQCrgsBBgDQA7gCFWA7QFYA6A+gCQAQhDgThLIgFgUQgIgYgJgSIFgAFICBAlIB0AiIA/ASIAFOGIhbAAQgxgRg9gRQh5ghg4gCQg3gBiJAmIh+AnIp5AKgABbHaQAtgQgCgeIgIAKQghArg+gBQAcAGAggMgAE2G8QgEAEgGACQgKAEgLACIgBABQgDAIgGAGIgCABQgGABAAAEIABACQAJAEAEgJIACgBQAFgDABgFIABgCQAMABAHgHQAKgJAKgDQAPgGAPgCQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBAAQgMgDgLAAQgLAEgHAIgAGGHRQAkgMANgbQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBABgBAAQgqArg+gCQAcAIAggLgAQJG+QAlAJAfAKQgZgVgjgIQgrgJgrgPQAbAVAzANgAEYGEQgmA6hHARQAigBAngWQA1gdAJg5QgNAPgNATgALGFpIg1ANQgYAFgVAMQgfASggAQQgQAJgOANQACABADAAIAEAAIAEgCIAGgCIABgBIABgCIAAgCIAAgCQAWgHASgKQAogWAtgMQBigZBdAXQADAGAFAFIgFgMQgGgKACgLIABgGQAPAaAbAMQgKgLgMgHQgFgDgFgFQgFgHgEgJQAEgTAGgSQgIAMgFARQgEgOAAgOQgDAHABAMQACAHACAGQgFAUAIAPQgcgMgggKQgUgFgVAAQgVAAgXAFgAQPC8QAOAjAQAjQAoBRgOBgQAMgpAAg1QABhBgqguQAWgVAAgfQAAgngagYQAEg7AMg4QAGgjgHglIgKgtIACAXQABBNgKBNQgEAiAEATIgFgEQglAeAVAxgAJUEUQgmApg6APQhXAXAJBNQAEhKBKgTQA7gPAqgoQAegdgCgaQgNAZgUAWgAIIFzIg8A5QAogUAognQAvgvBBgPIgCgCQgGgCgFAAQhDARg0AzgAQWEcQApBKgwA2IABACQAtgXgQg/QgVhKgjhEQAFAvAcAzgAJPC/QgpBShfAYQhjAYANBUQgBhLBPgWIAagHQB7giAIhwQgEARgJATgAO8B5QgDAjAJAiQAdBsAVBmQADhDgchFQgrhmAfhoQgPAbgEAkgANqhrQgFBMAWBDQAeBbgPBeQgUB0BbA7QgjgggagvQgJgRACgVQAViYgriLQgehiAxhSQgcAjgEAygAKXEZQAFATAOAMQgKAIgIAKQgJAMgHAPQAFAAADgIQAKgVAUgNQAKAIAPAEQgNgFgKgJQANgHgDgDIgNAHQgHgGgEgJIgGgOIARgBQARgCAMgFQAJAWAZAHQgQgJgKgQIgDgGQAMgHAIgMIgFAEIgSAJQgHgUAIgUQgJAJABAPQAAAKADAIQgWAJgXACQgIgaAIgcQgIANAAASQABANACAKQgLABgMgBQAMACAMABgAMFEwQAiAKAdAOQgWgYgkAAIgFAAgANsErQgPgKACgSIACgHQAKAFANABIgWgLQAEgRAJgPQgLANgFAQIgBABIgBAAIgMgIQALgOgDgSQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAABQAAAIgDAGQgEAHgFAGQgHgGgFgIQAAAJAJAIQgMAOgSAGQAQAAANgKIAGgFQAHAFAIAEQgHAaAWALIAAAAgANPj2QhJB6BBB/QA1Brg7BeIgJADIgCABQgEAJgIAHQgSATgPAVQAMABAKgJQAVgRAIgaIAHgBIADgBQA8hcg2hpQg7hzBAhsQBLh+gyiBQAkBwg/BqgAIHDQQgDAngnARQATgEAPgTQAVgZgKgiIAAAAIgDAagAKYDeIADgPIADgLIACAAQAVgDALgJIgFABIgbAFQAIgQASgJQAOgGAAgFQgcAKgOAZIgBACIgXADQAJADALgBQgEANACANgAIXCvQAFAJAHAGQgDAGAAAIQABAHAEAFIAFAAIAAAAIABAAQgMgMAHgLQAKAHAOABIgGgDQgHgEgIgGIAAAAIADgDQAPgOAPAGQgCgEgFAAIgIgBQgNAEgIAKQgMgLgFgOQgEAGAGAIgAMVBHQgGBdhKAvQBJgdAOhPQAQhjgwhXIgEgHQAiBNgFBUgAKxgJQAaBrhMBOQAQgHANgSQBAhZguhlIgKgYIANA2gAI0A+QAGA7gTAxQAYgVACgyQAEhBghgwQAKAeAGAugAJ1CjQgNgLgGgPIgBgGQAIgHALgFIAWgKQgYACgSAQQgFgSADgTQgFALABAPIACAOQgKAKgHAKQAEABACgDQAFgHAHgGQAFATATAJIAAAAgAN8BvQAEAbgHAWQALgQgBgWQAAgYgNgQIABgJQAAgXgKgTQgDAAgBgDIgCgFQAHgGACgIIgJAIIgRAOQAHgBAHgFQAAACADADQAIALACAOQACAMgBAKIgHgFIAGAIQgBANgEALQAGgIADgKQAFALACAOgAIbCdQgFgEgDgGIgCgCIABgBQAQgJgEgPIgEAIQgFAIgGAFIgGgFQgBADADAGQgFAEgHAEIAOgGQAFAIAJACgAMvBnIgBADIAAACQAIAGAFAIQgGAQgTAKQATgDAHgUIABgBIACADQAGAKACAKQADgKgHgJQAFgCADgGQADgIgBgIQgDADgCAGIgFAOIgBgBIgEgFQAIgYgJgXQAAAJABAOQABAMgDAKIgMgRIgBABgALOB9QgBgTAIgSIAEgIQAGAGAHAKQAHAKAAAMQAGgJgGgKQgHgNgNgHQAKgUAOgPQgTAOgLAWQgLAWAGAXIAAAAgAPnjFQAOAnAKApQAMAtgCAtQgCBQggBAQAWgMADgcQAEgrAIgrQARhpgyhbQgHAAADAIgAIHBvQAMgPACgTQAHgMgBgLIgFALIgBABIAAgHIgEgUQAIgQgBgSIgHAUIgCAGQgHgZgQgSQgDACADAFQAQAQAGAWQgGAPgJANQALgHAGgMIABgBQADAQgBAPQgGAKgHAIQAGgDAFgGQgCAPgIAPgAKfAvIAAAGIABAXIAAANQAEgDgBgEIgBgXIgBgOIgJgGIAFgLIAGAEIgFgFQADgLgBgMQgDAGgCAKIgBAEIgJgKQgNgOABgSQgEAIAFAKQAHAPANALIgFALQgIgFgIgDQAAAEAMAGIACABQgGAIgKAGQALgBAIgMIAJAGgAJcA2QgBATgQAMQAKgFAGgLQAKgOgHgRQgBAGgBAKgAI+jUQgUAyAYAuQA1BggGBlQAJABABgKQAFhUgthNQgshMAqhPQAzhfAEhoQgZB0gxBzgAPoAjQAKgngZgkIgKgRQAUAvAFAtgALiAIIARATQAJAGAHgGQgEgEgKACIgMgQIgHgHIAHgGIAEgHQAEALAHAJIgHgTIgCgFQAHgNAAgPIgBAAQgDALgFAJQgBgKABgJQgFAJADANIAAAAIgNAUQgGgEgJgEIAAgCQAAgBgBAAQAAgBAAAAQAAAAAAAAQgBgBAAAAIAAAAQgBAAAAABQgBAAAAAAQAAAAAAABQAAAAABABIABAEQAIAEAIAEIgIAPIALgMIACADgAI7gHQADAKAIAHIgCADQgEAGACAHIAGgOQAHAFAJABQgIgEgGgGQADgGAFgCIgBAAIgDgBIAAABIgGAGIgCgBQgLgKABgRQgDAGACAJgAO+AJQAIgMgIgSIgEgGQAIgJACgLQgFAEgDAGIgEAGQgIgLgLgIQAKgKABgNIgKAOIgFAFIgEgCQgDgCgBgDQgMgeAUgZQgOAMgDATQgDAUAPAJIAEADQgLANgNAJQAEAAAHgCIAQgPIACgCQALAJAHALQgOAQgXAFQAOADANgJQAHgFAFgFQAHAQgCASgANbgFQgEgMgJgLQgJgKgEgMIALAGIACACQAEAEADAGQACAGAEAEQgBgLgJgJQgIgIgJgGIgBgEIAAADIgIgEQgDADAJAFIADACQABAFACAGQAMAUAMAPIAAAAgALRggQgCgMADgLQgJANAIAKgAEXi1QArAWAtALQBhAWAkBUQgHgwgsgZQgigTgpgTQhzg2h2grIAAAAQA/AfBLAmgANWg+QAGAOAGACQgDgLgHgMQgEgJgHgGQgEgFgFgDQgBAAAAAAQgBAAAAABQAAAAAAAAQAAABABAAIgHgCIgBAAQAIAEAHAHQACAEAAAFQACAQADAJQABgKAAgKIAAgDIAEAIgAIXg9QgIAHgIAFQAKgDAJgHQAQAIAYgFIgBgBQgWAEgPgHIACgCQAQgPABgUQgBAIgHAJQgGAKgJAIQgGgEgGgGIAFgFQAQgRAEgWQgEAJgHAKQgIALgJAKIgCgEQAAgFgBgGQgCgHgBgHIgBAAQgCABAAAEQACALAFAKIACADIgRARQAFACADgDIAMgLQAEAGAHAEgAKBhjQgJAUAEASQABgPAFgNQAJgVALgQQgNALgIAQgAPHhLIAEAJQgPgpAWgoQgfAcAUAsgALbhpQAGATgGAQQALgUgJgXQgDACABAGgANkhQQgFgTAAgVQAAgXgHgVQAHgEAIgCIgBgBIgFgBIgKAFIgEgLIADAMQgNAHgJALQgIAJgBALQAHgNALgLQAGgHAHgEQACAMAAANIABAQIgEgGQgJgLgPABQAQACAJAQIAEAGQADASAHAQIAAAAgAM+h1IAAABQAPACAJAQIAGAKQACgKgIgIQgIgLgOAAIgCAAgALEiXIAFAIIgEAEQgSARABAUQAGgVARgRQANARAVABQgNgGgLgIIgHgGIAKgJIACgCQASgNAUgHIgBgBIgDgBQgSAHgPALQgBgRAHgOQAGgLgEgEQgFAMgEANQgDALABAMIgNAKQgHgKAAgNQgFAHAFAKgAHWhqIgNgWIgFgLQAMAFAMABIgZgIQgDgKgBgLQgDAIADAMIgDgBIgHgDIALAGIAAAAQAHAXAPALIAAAAgAK0kTQgqBKAOBTQgGhEAlhDQAwhZAAhnQgEBagvBQgAPIliQgEAhgSAZQglA1ABAzQABAcAMAbQgKgZADgbQAIg5AjgpQgBgGADgGQAEgFgBgIIADgCQAEgCADgDIAFglQAFgcgGgZQgGAXgEAggAJfjWQAEATANAIIgFALQgFAQADAOQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgTAKgPQAJADALAAQgKgBgJgFIAIgPQgHAFgFAGIAAAAQgPgNgDgUIgBAAQgCAFACAFgAQYisQAGAMAFAMQgWhPgfhJQAFA/AlBBgAFGjdQAsAJAyAYQAfAPAhANIACAGIABADIACABQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAIABgCQgXgcgmgRQgygYg3AAgAGjifIAEADQgHgIgCgNQgEAJAJAJgAISidQgCgPgIgNIAEgGQAJgQgBgSIAGgBQAbgFAGgXIAAAAQgGAJgJAHQgLAIgNAEIgCgPIgCAQIgNABIANAAIgBAIQgBAQgHAMIgEgFQgRgWgegKQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAABABQAbALAPAVIAFAJQgGAJgJAHQAKgFAHgJIANAYIAAAAgAPBirIgCgPQgEgQAGgNQAIAEAJABQAAAUAHAKQgDgMAAgNIAAgFIALgBIAAAAIgLgCQACgPALgKQgPAIgBARIgHgCIgKgEQAEgGAGgGQAJgJgCgEQgNAKgGAOIgLgGIgBAAQAAAAgBAAQAAABAAAAQAAAAAAABQABAAAAAAIALAIIgDAHQgGAXALAPIAAAAgALGjjQAEAYgNATQAMgIACgSQACgZgKgTIADAbgAQ2lIQAMBLAbA/QgEgtgPguQgUhEAJhFQgRAoAIAygANZjLQAFAHAJADIAMgIIAEAHIgDgIIADgBQAJgIABgMIgKAMIgDAEQgBgHADgJQAFgVAKgQQgMALgGASQgFAPADAMQgMALgNgNIABADgAEcjPQgEgDgDgCQgNgHgFgLQgGgNgDgNIAlAHQgOgGgSgDIgFgBQgCgKAAgKQgDAIABALIgOgEIgDgJIAAAJIgVgIQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQALAGAMAEIABAEQAEASANAIQgHgIgDgJIgFgMIAHABIAGABIABADQADAmAiAJIAAAAgAMQkTIgFAIQgDAEgBAJQgCAKAHAPIAEAIIADgBIAAAAIgCgEQgCgBgFgOIAAgGIAAgGIABgFIABgEIAHgLIAPAMQAIAGAFAGIACgDQgEgFgIgGIgQgNIAEgDQADgBASABIADAAIAAgBIgBgBIgKgCQgLAAgFACIgFAEIgLgHIAHgMIAGgIIAEgFIgBgBQAWgWAHgkQAJgygRguIgEgJIABAJIADA2QADA4gZAsIgBAAIgJALIgIANIgGgDIgGgDIgCgBIADgHIgCgLIgEABIABAHQABAGgBACIgBABIgCgBIgIgDIgHgBIgBADIgCABIAHAAIAIACIAEABQgDAFgGADIgIAEIgGAEQgEACAAACIgCABIABAGQAEgHADgBIAQgKIAEgDIAEgFIABABIANAGIABABIgJANIgFAHIgEAHIgGALIgCAEIgCAGIgBAGIABABIACAAIACgKIAFgJIAFgJIAHgMIAJgOIALAHgAGWj1IABATQADgIAAgKQANAFAPACIgcgKIgBgFQgDgVgQgJQgKAIgIAKQgQgLgJgSQgBALANAKIAMAJIgBACQgIANgDANIAQgZQAPAJAQAGgAKFj4QARgIABgUIABgVIACgCQAXgUgDgdIgFAYQgDAKgIAGIgGAGIgBgcQgDANACAQQgOAKgQAIIAPgFQAJgDAHgFQACAcgUAUgAH1j8QApgHAAgUQgHAEgHACQg4ASgwgKQAiATArgGgAC0koQBbAEBNAdQhUgthpAHQgcACgbgCQAmAEAmABgAOUkUQAGAFADAHQACgHgGgHIgHgGIAFgHQAHgKABgLQALgFAFgJQgDAAgDADIgJAHIgBgNIgFAQQgKAEgNAAQALADALgEQgDAOgHAKIgHgEIAEAGIgJAIQAHgBAFgEIAFAFgAQGk2QAGAVgBAWQAGgSgGgVQgEgRgMgMQAJgbgVgWQgCACADAFQAKALAAANQAAAJgBAHQgHgGgKgEIAAAAQAJAFAHAIQgGAVgVANQATgIAJgVIABgDQAHAKAFAMgAM1lAQAAAOADAMIAEghQACgVAYgCIgBgBIgDgBQgdAEAAAcgAgQk/QAfAHAiAFQg7gMg3gdQAFAUAsAJgAQPleQgEAdAWALQgNgLgBgPQgEgYAPgQQgNAKgCAQgAodlNIhAATQAdACAegGQAegGAegMIAIgDQBAgXBGAAQgBgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgMgCgMgBQhYAGhTAcgAMOlEQgDgCgEgBQgIgEgEgHIgCgGQAKgHAJgLQASgYgEgdIgFAYQgHAcgWASQgEgOAAgOQgDAGAAAKQAAAJADAGIgFAEIAFgDQAGAPAUACIAAAAgANcmFQAFAagEAZQAIgPgDgUQgCgbgIgYQAAAQAEATgAI+mUQADAfAHAWQAEgWAAgYQAAgjgZgTQAIATADAcgAK7lgQANgMADgVIAAgQQAZgWgUgbIgBABQAEAGAAAHQABAUgJAMQgBgSgJgRIAGAiIAAAFQgIAIgPADIADgGQADgLAAgJQAIgIgBgMQgBAIgGAFQgDgOgOgKQANAKgBASQgOANgOAKIAWgLIAGgDQgCALgEAKIgPABQAHABAHAAQgFANgIAKQALgJAHgPQAMgCALgIIACgBQACAZgPAVgAORliQAFgBAFgGQAIgOACgPIAAgMIAJgEIANgIIAAABQADAcgNAYQAPgQABgYQAAgJgCgIQAMgLAHgPQgGAFgFAGIgJAKQgHgTgUgLIAAAAQASAMAFAVQgKAJgMAFQgDgYgVgRQgBAAAAAAQgBABAAAAQAAAAABABQAAAAABABQAPAPAFAUIABAEQgKAFgNABQAMACAMgEQADAbgUAUgAGKj9QgKgDgIgGIAEgGQAEgFAFgBQAOgBABAUIABAGIgLgEg");
	this.shape_2.setTransform(368.2,38.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// bg
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(255,153,0,0.4)").s().p("EglfAGjIAAtGMBK+AAAIAANGg");
	this.shape_3.setTransform(240,42);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(238.4,25,486.9,107.4);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;